# Plugins
plugins:
 - jekyll-paginate

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Cole Strode
tagline: 'Hey there 👋'
description: 'Knitting needles, running shoes, and a love for all things spooky'
url: http://colestro.de
baseurl: /

author:
  name: 'Cole Strode'
  url: http://colestro.de

paginate: 5

# Custom vars
github:
  repo: https://github.com/colestrode/colestrode-site

socials:
  github:
    title: Github 
    url: https://github.com/colestrode
  linkedin:
    title: LinkedIn 
    url: https://www.linkedin.com/in/colestrode/
  ravelry:
    title: Ravelry 
    url: https://www.ravelry.com/projects/colestrode